### ISSUE TITLE
NFR : group cashing

### ISSUE THREAD

**Issue by Menta2L** [vicanso/pike#12]
First of all want to admire your project. Its the best and most complex opensource cashing software out there. Keep the good work!

Second i like to propose several new new feature requests and if possible to discus them (from what i see form the code you have impressive knowledge about http protocol specially in the optimization aspect)

First proposal is about several instances that use  a distributed cache: 
Ref : [https://github.com/golang/groupcache](https://github.com/golang/groupcache)

Second is related to abstraction of the upstreams.
To be able to handle GCS or S3 buckets as upstream

Third one is for UI : options to display some statistics like miss/hit ratio and ability to purge cache entries.

And documentation is a bit foggy Took me about a 3 days to run the app with my scenario but at the end results are impressive !

**Comment by vicanso** [comment]
@Menta2L Thanks for your suggestion. The version 3.0(master) is still under development,  which I will improve and release asap.

**Comment by Menta2L** [comment]
I found one very interesting package related to distributed cache that may be interesting 

[https://github.com/vimeo/galaxycache](https://github.com/vimeo/galaxycache)

**Comment by vicanso** [comment]
Pike is used for short http cache mainly and `lru` cache is more suitable. In production I will use nginx -->(url hash) N pike for better performance and high availability. May I ask the reason you suggest distributed cache.

**Comment by Menta2L** [comment]
Yes will try to explain its a bit of edge case.
lets say that i like to cache tons of images (about a million) each image is with avg size of 80KB that is about of ~75GB cache stored in ram in a single server Honestly i am not sure even how lru can handle this I did not do such a benchmarks yet.
Anyway varnish have such a distributed cache (a little complicated and a bit expensive but they have it )

**Comment by vicanso** [comment]
Pike is support badger and redis for store
