### ISSUE TITLE
压测有如下错误：ReverseProxy read error during body copy: context deadline exceeded

### ISSUE THREAD

**Issue by akin520** [vicanso/pike#18]
日志中返回400，日志中能否看出是否被命中，从日志中看好像全部打到源服务器去请求了

**Comment by akin520** [comment]
{"level":"info","ts":"2021-01-20T16:00:09.697+0800","caller":"server/server.go:316","msg":"10.1.103.251:34379 2021-01-20T16:00:09+08:00 http://1.1.1.178:80 GET / HTTP/1.1 400 46B - -"}
{"level":"info","ts":"2021-01-20T16:00:09.698+0800","caller":"server/server.go:316","msg":"10.1.103.251:34362 2021-01-20T16:00:09+08:00 http://1.1.1.188:80 GET / HTTP/1.1 400 46B - -"}

**Comment by akin520** [comment]
正常情况
{"level":"info","ts":"2021-01-20T16:00:09.595+0800","caller":"server/server.go:316","msg":"10.1.103.251:34388 2021-01-20T16:00:09+08:00 http://1.1.1.178:80 GET / HTTP/1.1 200 12.94KB - -"}
{"level":"info","ts":"2021-01-20T16:00:09.605+0800","caller":"server/server.go:316","msg":"10.1.103.251:34400 2021-01-20T16:00:09+08:00 http://1.1.1.188:80 GET / HTTP/1.1 200 12.94KB - -"}

**Comment by vicanso** [comment]
接口的缓存状态记录在响应头`X-Status`中，如果需要在日志中输出，将日志的template中添加`{<x-status}`则可，如：`{remote} {when-iso} {:proxyTarget} {method} {uri} {proto} {status} {<x-status} {size-human} {referer} {userAgent}`。

接口是否有缓存基于`Cache-Control`，先确认一下接口的响应头是否有设置`Cache-Control`而且没有`Set-Cookie`。

`context deadline exceeded`为超时，确认一下location中的proxy timeout的值，如果过短则调整此值。
