### ISSUE TITLE
打不开管理主页

### ISSUE THREAD

**Issue by liaohongxing** [vicanso/pike#19]
版本 
v4.1.0  windows x64 

启动命令 :
.\pike.exe --admin=:9013

访问 127.0.0.1:9013 出现错误：

{"statusCode":500,"category":"elton-error","message":"open web\\index.html: file does not exist","exception":true}

**Comment by vicanso** [comment]
由于管理后台embed打包，文件路径应该是web/index.html，因此在windows平台上会有此问题。这个问题我尽快修改，你可以先使用docker版本

**Comment by vicanso** [comment]
已在4.1.1版本中修复此问题，麻烦试试

**Comment by liaohongxing** [comment]
可以了 ，管理页面是 flutter 写的吗

**Comment by vicanso** [comment]
是的，当时flutter web准备出正式版本，所以就尝试了一下
