### ISSUE TITLE
如何配置某个url缓存多长时间

### ISSUE THREAD

**Issue by luger1990** [vicanso/pike#6]
1、如何配置某个url缓存多长时间
2、能否根据参数配置缓存的key，比如参数是 a=1&b=2&c=3&d=4 其中c和d参数都无用，只想根据a b参数缓存
3、能否根据resp header判断是否缓存，缓存多长时间（varnish支持）

**Comment by vicanso** [comment]
1. 缓存的时间基于响应头的`Cache-Control`，规则如下：
  - 如果响应头有`Set-Cookie`则不可缓存
  - 如果响应头没有`Cache-Control`则不可缓存 
  - 如果`Cache-Control`包括 no-cache|no-store|private，则不可缓存
  - 从`Cache-Control`中优先取`s-maxage`做为缓存时间，如果没有，则取`max-age`

2. 生成缓存的Key是`Method + Host + RequestURI `（浏览器的缓存形式也是如此），后续会支持自定义，但如果要达到你所要求的从query中筛选，这个因为生成缓存Key的是公共的，不太可能用这种方式。您是什么场景需要这么细化的缓存Key的生成？

3. 参考1的回复
