### ISSUE TITLE
大佬windwos编译失败...

### ISSUE THREAD

**Issue by shuyabin** [vicanso/pike#7]
![image](https://user-images.githubusercontent.com/14884581/43678330-328e2364-9844-11e8-8670-b1dc07615c96.png)

但是我看了一下.. decoe.h 文件是存在的。。

**Comment by shuyabin** [comment]
然后跑linux 上运行了一下 我吧 decode 移到了当前go的子（google/brotli/go/cbrotli）目录...emmmm
![image](https://user-images.githubusercontent.com/14884581/43679030-7a52e584-9850-11e8-94e4-3a529c54c3a2.png)
![image](https://user-images.githubusercontent.com/14884581/43679222-49b94e28-9854-11e8-9af4-dcae2c6cce08.png)

**Comment by vicanso** [comment]
@shuyabin  windows我没有编译过，因为brotli的编译不会搞。linux的编译可以参考dockerfile

**Comment by vicanso** [comment]
最新版本已支持通过指定编译参数按需加载brotli
