### ISSUE TITLE
docker 按照官网手册运行不成功

### ISSUE THREAD

**Issue by shuyabin** [vicanso/pike#8]
![image](https://user-images.githubusercontent.com/14884581/43678899-4dc7254a-984e-11e8-8e7b-78aa2d1f856e.png)

![image](https://user-images.githubusercontent.com/14884581/43678901-55839b1a-984e-11e8-9f00-16bbb9362725.png)

![image](https://user-images.githubusercontent.com/14884581/43678921-be58af72-984e-11e8-8455-dc966b3e4223.png)

docker run -d --restart=always -p 3015:3015 -v ./config.yml:/etc/pike/config.yml vicanso/pike
不知道是不是我服务器的问题。。 docker映射目录一定要绝对路径吧。。

**Comment by shuyabin** [comment]
- -反应过来是..镜像里面没有吧后台页面放进去。。尴尬 ( 文档是否需要说明一下。。) 然后大佬有个问题... 如果是域名的是不是的backends里面直接设置域名+端口就可以了?   -- 这样怎么做到和nginx那样多域名的方式? 一台服务器不同的域名访问 缓存不同服务器(域名)的请求。。

**Comment by vicanso** [comment]
@shuyabin  不好意思，管理后台是有打包的，但是最新版本的后台管理地址是`adminPath` +"/index.html" 这样，官网上的文档没有更新，可以试一下测试网址：`http://xs.aslant.site:3000/pike/index.html`，token是`abcd`。

多域名缓存可以查看[issue6](https://github.com/vicanso/pike/issues/6)
